[package]
name = "mimic"
version = "0.1.0"
authors = ["MarWit <contact@marwit.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rand_distr = "0.4"
ndarray = "0.14"
ndarray-rand = "0.13"
