[package]
name = "project"
version = "0.1.0"
authors = ["MarWit"]

[dependencies]
rustfft = "*"
alsa = "*"
rb = "*"
nalgebra = "*"
sprs = "*"
ndarray = "*"
num-complex = "0.1.43"
num-traits = "*"
num-derive = "*"
lazy_static = "*"
