condense_wildcard_suffixes = true
edition = "2018"
format_strings = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20
